ALTER TABLE submissions ADD COLUMN IF NOT EXISTS solved_at DATETIME;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS next_review_at DATETIME;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS review_count INT NOT NULL DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS last_review_feedback VARCHAR(50);
